// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmnmbhmyenbjpxwxuces.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbm1iaG15ZW5ianB4d3h1Y2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTE1NDUsImV4cCI6MjA2MTkyNzU0NX0.dcub88L8MS3u72Ey-3FeJ8dl1FtwSOpI-qAKO1YSrko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);